apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: my-app-3
  name: devfile-sample
spec:
  rules:
  - host: devfile-sample-pshivpuj-tenant.$121.ip.io
    http:
      paths:
      - backend:
          service:
            name: devfile-sample
            port:
              number: 3001
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
