apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-deoc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-deoc
    app.kubernetes.io/part-of: my-app-3
  name: netlifytrial-deoc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: netlifytrial-deoc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: netlifytrial-deoc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/my-app-3/netlifytrial-deoc@sha256:c7c52c1b2d677c8534bc8d6d5f37f9eddc7bb7d37eec950bf27094b9a6c965c7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
